"""
Clustering Algorithm Comparison on Depth Maps: KMeans, MiniBatchKMeans, GMM, DBSCAN.

Requires pre-computed depth maps (.npy) in data-dir/Depth/.
Run depth_models/pipeline.py first to generate them.

Usage:
    python clustering/clustering_comparison.py --data-dir sample_data
"""

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image
from sklearn.cluster import KMeans, MiniBatchKMeans, DBSCAN
from sklearn.mixture import GaussianMixture

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from eval_utils import (
    resolve_dataset_dirs,
    load_gt,
    compute_metrics,
    save_visual,
    save_csv,
    save_prediction_map,
    IMAGE_EXTENSIONS,
)

METHODS = {
    "KMeans": lambda: KMeans(n_clusters=2, random_state=42, n_init=5, max_iter=100),
    "MiniBatchKMeans": lambda: MiniBatchKMeans(n_clusters=2, random_state=42, batch_size=4096, n_init=5, max_iter=100),
    "GMM": lambda: GaussianMixture(n_components=2, random_state=42, max_iter=50, covariance_type="spherical"),
    "DBSCAN": lambda: DBSCAN(eps=0.05, min_samples=30, n_jobs=-1),
}

INVERSE_DEPTH_MODELS = {"Depth Anything", "Dpt large"}
SAMPLE_RATIO = 0.02


def cluster_depth(depth, method_name, method_fn):
    """Cluster a depth map into binary plant/soil mask."""
    flat = depth.reshape(-1).astype(np.float32)
    if float(np.std(flat)) < 1e-6:
        return np.zeros(depth.shape, dtype=np.uint8)

    n = min(flat.size, max(2, int(flat.size * SAMPLE_RATIO)))
    rng = np.random.default_rng(42)
    samples = flat[rng.choice(flat.size, n, replace=False)].reshape(-1, 1)

    if method_name == "DBSCAN":
        r = float(samples.max() - samples.min())
        clusterer = DBSCAN(eps=r * 0.05, min_samples=30, n_jobs=-1)
    else:
        clusterer = method_fn()

    clusterer.fit(samples)

    if hasattr(clusterer, "cluster_centers_"):
        centers = clusterer.cluster_centers_.reshape(-1)
    elif hasattr(clusterer, "means_"):
        centers = clusterer.means_.reshape(-1)
    else:
        labels = clusterer.fit_predict(samples)
        unique = np.unique(labels[labels != -1])
        if len(unique) < 2:
            return (flat > np.median(flat)).astype(np.uint8).reshape(depth.shape)
        centers = np.array([samples[labels == u].mean() for u in unique[:2]])

    centers = np.sort(centers)
    dists = np.abs(flat[:, None] - centers[None, :])
    return np.argmin(dists, axis=1).astype(np.uint8).reshape(depth.shape)


def preprocess_depth(depth, model_name, invert_depth=False):
    """Normalise depth to [0, 1], with optional inversion for legacy disparity maps."""
    depth = np.nan_to_num(depth, nan=0.0, posinf=0.0, neginf=0.0)
    if invert_depth:
        mx = depth.max()
        if mx > 0:
            depth = mx - depth
    lo, hi = depth.min(), depth.max()
    if hi - lo > 0:
        depth = (depth - lo) / (hi - lo)
    return depth.astype(np.float32)


def main():
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("--data-dir", "--data-root", dest="data_root", default="sample_data")
    parser.add_argument("--folder", default=None,
                        help="Optional subfolder to process under --data-root.")
    parser.add_argument(
        "--depth-root",
        default="outputs/all_methods/depth_models/depth_anything/depth_maps",
        help="Root directory containing depth maps generated by depth_models/pipeline.py",
    )
    parser.add_argument("--depth-subdir", default="Depth", help="Subfolder with .npy depth maps")
    parser.add_argument("--depth-model", default="Depth Anything", help="Depth model label (for logs/compatibility)")
    parser.add_argument(
        "--invert-depth",
        action="store_true",
        help="Invert depth before clustering. Use only for legacy disparity maps.",
    )
    parser.add_argument("--output-dir", default="outputs/all_methods")
    args = parser.parse_args()

    dataset_dirs = resolve_dataset_dirs(args.data_root, args.folder)
    out = Path(args.output_dir) / "clustering"
    depth_root = Path(args.depth_root) if args.depth_root else None

    # Resolve one depth directory per dataset once, before running methods.
    depth_dir_by_dataset = {}
    searched_roots = []
    auto_depth_roots = [
        Path(args.output_dir) / "depth_models" / "depth_anything" / "depth_maps",
        Path(args.output_dir) / "depth_models" / "depth_pro" / "depth_maps",
        Path(args.output_dir) / "depth_models" / "dpt_large" / "depth_maps",
    ]

    for dataset_dir in dataset_dirs:
        dataset_name = dataset_dir.name
        candidates = []
        if depth_root:
            candidates.append(depth_root / dataset_name)
        candidates.extend(root / dataset_name for root in auto_depth_roots)
        candidates.append(dataset_dir / args.depth_subdir)  # legacy fallback

        found = None
        for cand in candidates:
            searched_roots.append(cand)
            if cand.exists() and any(cand.glob("*.npy")):
                found = cand
                break

        if found is None:
            print(f"No depth maps found for dataset: {dataset_name}")
            print("Searched:")
            for cand in candidates:
                print(f"  - {cand}")
            print("Run depth_models/pipeline.py first to generate depth maps.")
            return

        depth_dir_by_dataset[dataset_name] = found

    for method_name, method_fn in METHODS.items():
        records = []
        vis_dir = out / method_name / "visuals"

        for dataset_dir in dataset_dirs:
            dataset_name = dataset_dir.name
            depth_dir = depth_dir_by_dataset[dataset_name]
            gt_dir = dataset_dir / "Ground Truth"
            rgb_dir = dataset_dir / "RGB"

            depth_files = sorted(depth_dir.glob("*.npy"))
            if not depth_files:
                print(f"No .npy files in {depth_dir}")
                continue

            for df in depth_files:
                gt_path = gt_dir / f"{df.stem}_mask.npy"
                rgb_path = next((rgb_dir / f"{df.stem}{ext}" for ext in IMAGE_EXTENSIONS if (rgb_dir / f"{df.stem}{ext}").exists()), None)
                if not gt_path.exists() or rgb_path is None:
                    continue

                depth = preprocess_depth(np.load(df), args.depth_model, invert_depth=args.invert_depth)
                gt = load_gt(gt_path)
                rgb = np.array(Image.open(rgb_path).convert("RGB"))

                pred = cluster_depth(depth, method_name, method_fn)
                plant_mask = (pred == 0).astype(np.uint8)
                metrics = compute_metrics(plant_mask, gt)
                records.append({"dataset": dataset_name, "image": df.name, **metrics})
                save_visual(
                    rgb, plant_mask, gt,
                    vis_dir / dataset_name / f"{df.stem}.png",
                    method_name,
                )
                save_prediction_map(
                    plant_mask,
                    out / method_name / "prediction_maps" / dataset_name / df.stem,
                )

        save_csv(records, out / method_name / "results.csv")
        print(f"{method_name}: {len(records)} images -> {out / method_name}")


if __name__ == "__main__":
    main()
